name: Build LaTeX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: curriculum.tex
        
    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: curriculum-pdf
        path: curriculum.pdf
